Dev
BSUIR-OOP/laboratory-work-1-ilyaVdovenko1 pull request #1
Opened 2022-03-13 22:14 UTC by ilyaVdovenko1

Merge Dev to Main: Added fully working first lab that ready for code rewiew.

2022-03-15 09:40 UTC, GlebTheProgrammer commented
<h3>Ну что ж, пора и мне высказать своё мнение по поводу твоей реализации :)</h3>

1. Название переменной не должно содержать название типа (string stringRepresentation). Как минимум это выглядит ну ооочень странно;
2. разграничивать предметные области является необходимой задачей, так как открывать в проект, в котором перемешаны и абстрактные, и простые классы, а также каким-то образом и csproj в одном месте очень больно для глаз;
3. добавление интерфейса с необходимыми методами и реализация их в дочернем классе. Всё таки по статистике интерфейсы имеют больший охват, нежели абстрактные классы, причем интерфейсы сразу показывают тебе, что ты не реализовал тот или иной метод. Если будешь на прикладном уровне изучать Core, то там практически никто не использует абстрактные классы, так как всё делается при помощи интерфейсов, который в свою очередь позволяют корректно реализовывать dependency injection;
4. скорее субъективщина, но всё же... Если взять класс Quadrangle, в котором реализованы 2 конструктора. Почему тот же самый вывод у тебя происходит в конструкторе дочернего класса, ведь это всё можно сделать в самом унаследованном классе, и не тянуть эти поля в дочерний класс. Если у тебя будет необходимость добавлять ещё какие-то поля в Rectangle, ты их тоже будешь отправлять на обработку в Quadrangle? А если необходима будет какая-то новая реализация унаследованного от Quadrangle класса, ты будешь создавать ещё один конструктор? Я бы задумался о переносе логики работы с конкретным объектом в класс конкретного объекта.

2022-03-15 10:03 UTC, ilyaVdovenko1 commented
1. В данном случае строковое представление это указание не на тип а на метод представления
2. Не вижу особого смысла городить доп. иеархию неймспейсов, при работе над 2 лабой я это учту
3. Этот код нацелен на то что я могу использовать наследование, понятное дело что DI можно использовать, но для этого у нас будет отдельная лаба
4. Да, система создания фигур могла бы быть другой, но не вижу в этой больших проблем.
P.s Этот вопрос специально был уточнен, List-а для 1 лабы достаточно
Но спасибо за некоторые дельные замечания:)

2022-03-17 07:20 UTC, WildTiger404 commented
![image](https://user-images.githubusercontent.com/22522346/158757117-e40416db-d064-4055-b0fb-c6ebb246bd04.png)

2022-03-17 07:38 UTC, WildTiger404 commented
Дельные замечания это те, после которых вносятся изменения

2022-03-17 08:06 UTC, WildTiger404 requested changes

2022-03-17 08:06 UTC, WildTiger404 commented on Lab1App/Dot.cs
> +    private readonly string stringDrawDotRepresentation;
I don't understand. You already have two conventions. stringRepresentationOfDrawingCircle and stringDrawDotRepresentation. Why not stringRepresentationofDrawingDot? Choose only one convention in all cases. I like DrawRepresentation variant, because in that case you can avoid using type in a name(that is basically bad practice to use basic type in a name, but with exceptions)

2022-03-17 08:06 UTC, WildTiger404 commented on Lab1App/Dot.cs
> +    private readonly string stringDrawDotRepresentation;
So I suggest drawDotRepresentation here, for example

2022-03-17 08:06 UTC, WildTiger404 commented on Lab1App/Dot.cs
> +    /// Implements drawing dot logic.
![image](https://user-images.githubusercontent.com/22522346/158761546-efd84f45-3ede-4091-944f-bd8d25d59a3c.png)

2022-03-17 08:06 UTC, WildTiger404 commented on Lab1App/Figure.cs
> +    /// Figure screen start point.
![image](https://user-images.githubusercontent.com/22522346/158761794-787bc608-1220-4048-be70-de16e137e49f.png)

2022-03-17 08:06 UTC, WildTiger404 commented on Lab1App/Figure.cs
> +    /// Figure screen end point.
So the plot is. Whenever you use the name of the variable in comments to describe it that means this comment is useless. On the other hand when you need to use comments to describe a variable that means your variable name sucks.  Too many comments also is not good because you waste time without a good reason.

2022-03-17 08:06 UTC, WildTiger404 commented on Lab1App/Figure.cs
> +    /// Gets an uniq figure id.
![image](https://user-images.githubusercontent.com/22522346/158763471-ac1f12c7-6f5c-4fe4-896d-bf4a6e32af94.png)

2022-03-17 08:06 UTC, WildTiger404 commented on Lab1App/Figure.cs
> +    /// An uniq figure id.
![image](https://user-images.githubusercontent.com/22522346/158763498-731bc2d3-c19a-471a-b0ae-07457555aa94.png)

2022-03-17 08:06 UTC, WildTiger404 commented on Lab1App/Figure.cs
> +    /// Implements figure draw logic.
![image](https://user-images.githubusercontent.com/22522346/158763539-40a4c92f-c7ee-4157-bdc7-64b312aa47e1.png)

2022-03-17 08:06 UTC, WildTiger404 commented on Lab1App/Line.cs
> +    /// <param name="figureId">Uniq figure id.</param>
well, there are a million of it, so I stop here. I hope you understand the plot

2022-03-17 08:06 UTC, WildTiger404 commented on Lab1App/Program.cs
> +#pragma warning restore SA1200
???

2022-03-17 08:07 UTC, WildTiger404 commented
even if it's a simple task why not to have a good folder hierarchy? just a simple Classes would look better

2022-03-21 11:01 UTC, WildTiger404 approved these changes

2022-03-21 13:43 UTC, merged